version: '3.x'
services:
  minio:
    image: minio/minio:RELEASE.2023-02-27T18-10-45Z
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - ./minio.env
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
  aurora:
    container_name: aurora
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env
volumes:
  minio_data:
